### ISSUE TITLE
Update to use the DP+ 0.13.0

### ISSUE THREAD

**Issue by jqnatividad** [dathere/datapusher-plus-docker#5]

**Comment by minhajuddin2510** [comment]
Getting the below error while installing datapusher-plus docker version 0.13.0
Where are we setting the Python path configuration ?

`(default) minhaj@Ubuntu20:~/test-dp/datapusher-plus-docker/datapusher-plus/0.11.0$ docker compose up 
[+] Running 1/0
 ⠿ Container datapusher-plus  Created                                                                                        0.0s
Attaching to datapusher-plus
datapusher-plus  | ${VENV}/bin/uwsgi --socket=/tmp/uwsgi.sock --enable-threads -i ${CFG_DIR}/uwsgi.ini --wsgi-file=${SRC_DIR}/datapusher-plus/wsgi.py
datapusher-plus  | [uWSGI] getting INI configuration from /etc/ckan/datapusher/uwsgi.ini
datapusher-plus  | *** Starting uWSGI 2.0.21 (64bit) on [Mon Jun 19 20:42:33 2023] ***
datapusher-plus  | compiled with version: 11.3.0 on 19 June 2023 20:18:43
datapusher-plus  | os: Linux-5.15.0-71-generic #78~20.04.1-Ubuntu SMP Wed Apr 19 11:26:48 UTC 2023
datapusher-plus  | nodename: Ubuntu20
datapusher-plus  | machine: x86_64
datapusher-plus  | clock source: unix
datapusher-plus  | detected number of CPU cores: 8
datapusher-plus  | current working directory: /srv/app/src
datapusher-plus  | writing pidfile to /tmp/uwsgi.pid
datapusher-plus  | detected binary path: /usr/lib/ckan/dpplus_venv/bin/uwsgi
datapusher-plus  | !!! no internal routing support, rebuild with pcre support !!!
datapusher-plus  | setuid() to 33
datapusher-plus  | your memory page size is 4096 bytes
datapusher-plus  |  *** WARNING: you have enabled harakiri without post buffering. Slow upload could be rejected on post-unbuffered webservers *** 
datapusher-plus  | detected max file descriptor number: 1048576
datapusher-plus  | lock engine: pthread robust mutexes
datapusher-plus  | thunder lock: disabled (you can enable it with --thunder-lock)
datapusher-plus  | uWSGI http bound on 0.0.0.0:8800 fd 3
datapusher-plus  | uwsgi socket 0 bound to UNIX address /tmp/uwsgi.sock fd 6
datapusher-plus  | Python version: 3.10.6 (main, May 29 2023, 11:10:38) [GCC 11.3.0]
datapusher-plus  | !!! Python Home is not a directory: /usr/lib/ckan/datapusher-plus !!!
datapusher-plus  | Set PythonHome to /usr/lib/ckan/datapusher-plus
datapusher-plus  | Python path configuration:
datapusher-plus  |   PYTHONHOME = '/usr/lib/ckan/datapusher-plus'
datapusher-plus  |   PYTHONPATH = (not set)
datapusher-plus  |   program name = '/usr/lib/ckan/datapusher-plus/bin/python'
datapusher-plus  |   isolated = 0
datapusher-plus  |   environment = 1
datapusher-plus  |   user site = 1
datapusher-plus  |   import site = 1
datapusher-plus  |   sys._base_executable = '/usr/lib/ckan/datapusher-plus/bin/python'
datapusher-plus  |   sys.base_prefix = '/usr/lib/ckan/datapusher-plus'
datapusher-plus  |   sys.base_exec_prefix = '/usr/lib/ckan/datapusher-plus'
datapusher-plus  |   sys.platlibdir = 'lib'
datapusher-plus  |   sys.executable = '/usr/lib/ckan/datapusher-plus/bin/python'
datapusher-plus  |   sys.prefix = '/usr/lib/ckan/datapusher-plus'
datapusher-plus  |   sys.exec_prefix = '/usr/lib/ckan/datapusher-plus'
datapusher-plus  |   sys.path = [
datapusher-plus  |     '/usr/lib/ckan/datapusher-plus/lib/python310.zip',
datapusher-plus  |     '/usr/lib/ckan/datapusher-plus/lib/python3.10',
datapusher-plus  |     '/usr/lib/ckan/datapusher-plus/lib/python3.10/lib-dynload',
datapusher-plus  |   ]
datapusher-plus  | Fatal Python error: init_fs_encoding: failed to get the Python codec of the filesystem encoding
datapusher-plus  | Python runtime state: core initialized
datapusher-plus  | ModuleNotFoundError: No module named 'encodings'
datapusher-plus  | 
datapusher-plus  | Current thread 0x00007f9651218740 (most recent call first):
datapusher-plus  |   <no Python frame>
datapusher-plus  | VACUUM: unix socket /tmp/uwsgi.sock removed.
datapusher-plus exited with code 1`

**Comment by samibaig** [comment]
Fixed
